EES-5446 - added dummy long-running orchestration with which we can test the deploy delay of the Data Processor.

diff --git a/infrastructure/templates/public-api/ci/jobs/deploy-data-processor.yml b/infrastructure/templates/public-api/ci/jobs/deploy-data-processor.yml
--- a/infrastructure/templates/public-api/ci/jobs/deploy-data-processor.yml
+++ b/infrastructure/templates/public-api/ci/jobs/deploy-data-processor.yml
@@ -10,15 +10,16 @@ parameters:
 jobs:
   - deployment: DeployPublicDataProcessor
     displayName: Deploy Public Data Processor
+    condition: and(succeeded(), eq(variables.deployDataProcessor, true))
     dependsOn: ${{ parameters.dependsOn }}
     environment: ${{ parameters.environment }}
     strategy:
       runOnce:
         deploy:
           steps:
-            - download: MainBuild
-              displayName: Download Public API Data Processor artifact
-              artifact: public-api-data-processor
+            # - download: MainBuild
+            #   displayName: Download Public API Data Processor artifact
+            #   artifact: public-api-data-processor
 
             - template: ../tasks/bicep-output-variables.yml
               parameters:
@@ -27,41 +28,41 @@ jobs:
             # We do config updates out of Bicep template so we can implement slot swapping.
             # Changes are first deployed to the staging slot and combined with a fresh
             # code deploy prior to being swapped with the production slot.
-            - task: AzureCLI@2
-              displayName: Update staging slot app settings
-              retryCountOnTaskFailure: 1
-              inputs:
-                azureSubscription: ${{ parameters.serviceConnection }}
-                scriptType: bash
-                scriptLocation: inlineScript
-                inlineScript: |
-                  set -e
+            # - task: AzureCLI@2
+            #   displayName: Update staging slot app settings
+            #   retryCountOnTaskFailure: 1
+            #   inputs:
+            #     azureSubscription: ${{ parameters.serviceConnection }}
+            #     scriptType: bash
+            #     scriptLocation: inlineScript
+            #     inlineScript: |
+            #       set -e
                   
-                  az functionapp config appsettings set \
-                    --name $(dataProcessorFunctionAppName) \
-                    --resource-group $(resourceGroupName) \
-                    --slot staging \
-                    --settings \
-                      "App__PrivateStorageConnectionString=@Microsoft.KeyVault(VaultName=$(keyVaultName); SecretName=$(coreStorageConnectionStringSecretKey))" \
-                      "App__EnableThemeDeletion=$(enableThemeDeletion)" \
-                      "AZURE_CLIENT_ID=$(dataProcessorFunctionAppManagedIdentityClientId)" \
-                      "DataFiles__BasePath=$(dataProcessorPublicApiDataFileShareMountPath)"
+            #       az functionapp config appsettings set \
+            #         --name $(dataProcessorFunctionAppName) \
+            #         --resource-group $(resourceGroupName) \
+            #         --slot staging \
+            #         --settings \
+            #           "App__PrivateStorageConnectionString=@Microsoft.KeyVault(VaultName=$(keyVaultName); SecretName=$(coreStorageConnectionStringSecretKey))" \
+            #           "App__EnableThemeDeletion=$(enableThemeDeletion)" \
+            #           "AZURE_CLIENT_ID=$(dataProcessorFunctionAppManagedIdentityClientId)" \
+            #           "DataFiles__BasePath=$(dataProcessorPublicApiDataFileShareMountPath)"
                   
-                  az webapp config connection-string set \
-                    --name $(dataProcessorFunctionAppName) \
-                    --resource-group $(resourceGroupName) \
-                    --connection-string-type SQLAzure \
-                    --slot staging \
-                    --settings \
-                      "ContentDb=@Microsoft.KeyVault(VaultName=$(keyVaultName); SecretName=$(dataProcessorContentDbConnectionStringSecretKey))"
+            #       az webapp config connection-string set \
+            #         --name $(dataProcessorFunctionAppName) \
+            #         --resource-group $(resourceGroupName) \
+            #         --connection-string-type SQLAzure \
+            #         --slot staging \
+            #         --settings \
+            #           "ContentDb=@Microsoft.KeyVault(VaultName=$(keyVaultName); SecretName=$(dataProcessorContentDbConnectionStringSecretKey))"
                   
-                  az webapp config connection-string set \
-                    --name $(dataProcessorFunctionAppName) \
-                    --resource-group $(resourceGroupName) \
-                    --connection-string-type PostgreSQL \
-                    --slot staging \
-                    --settings \
-                      "PublicDataDb=@Microsoft.KeyVault(VaultName=$(keyVaultName); SecretName=$(dataProcessorPsqlConnectionStringSecretKey))"
+            #       az webapp config connection-string set \
+            #         --name $(dataProcessorFunctionAppName) \
+            #         --resource-group $(resourceGroupName) \
+            #         --connection-string-type PostgreSQL \
+            #         --slot staging \
+            #         --settings \
+            #           "PublicDataDb=@Microsoft.KeyVault(VaultName=$(keyVaultName); SecretName=$(dataProcessorPsqlConnectionStringSecretKey))"
 
             # TODO EES-5128
             # Add Private Endpoint to Data Processor Function App into the VMSS VNet to allow
@@ -97,20 +98,20 @@ jobs:
             # Client IDs / Identities that can access the Function App. The Service Principal
             # that is performing the deploy can be accessed by using the `addSpnToEnvironment`
             # config option in the task definition and using the $(servicePrincipalId) variable.
-            - task: AzureCLI@2
-              displayName: Deploy to staging slot
-              retryCountOnTaskFailure: 10
-              inputs:
-                azureSubscription: ${{ parameters.serviceConnection }}
-                scriptType: bash
-                scriptLocation: inlineScript
-                inlineScript: |
-                  set -e
-                  az functionapp deployment source config-zip \
-                    --src '$(Pipeline.Workspace)/MainBuild/public-api-data-processor/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.zip' \
-                    --name $(dataProcessorFunctionAppName) \
-                    --resource-group $(resourceGroupName) \
-                    --slot staging
+            # - task: AzureCLI@2
+            #   displayName: Deploy to staging slot
+            #   retryCountOnTaskFailure: 10
+            #   inputs:
+            #     azureSubscription: ${{ parameters.serviceConnection }}
+            #     scriptType: bash
+            #     scriptLocation: inlineScript
+            #     inlineScript: |
+            #       set -e
+            #       az functionapp deployment source config-zip \
+            #         --src '$(Pipeline.Workspace)/MainBuild/public-api-data-processor/GovUk.Education.ExploreEducationStatistics.Public.Data.Processor.zip' \
+            #         --name $(dataProcessorFunctionAppName) \
+            #         --resource-group $(resourceGroupName) \
+            #         --slot staging
 
             # TODO EES-5128
             # Add Private Endpoint to Data Processor Function App into the VMSS VNet to allow
@@ -137,30 +138,35 @@ jobs:
 
             - task: AzureCLI@2
               displayName: Wait for active orchestrations to complete
-              retryCountOnTaskFailure: 1
               inputs:
                 azureSubscription: ${{ parameters.serviceConnection }}
                 scriptType: bash
                 scriptLocation: inlineScript
                 inlineScript: |
                   set -e
+                  set -x
 
                   pollingTimeSeconds=5
-                  maxAttempts=24
+                  maxAttempts=50
                   attempts=1
                   
                   while [ "$attempts" -le "$maxAttempts" ]; do
                   
                     echo "Attempt number $attempts to check if the Data Processor is ready for deployment"
+                    echo "Calling $(dataProcessorFunctionAppStagingUrl)/api/StatusCheck to check for active orchestrations"
                       
-                    activeOrchestrations=`curl -s $dataProcessorFunctionAppUrl/api/StatusCheck | jq -r '.activeOrchestrations != 0'`
-
-                    if [[ "$activeOrchestrations" == "false2" ]]; then
+                    activeOrchestrations=`curl -s $(dataProcessorFunctionAppStagingUrl)/api/StatusCheck | jq -r '.activeOrchestrations != 0'`
+                    
+                    echo "Orchestration results are $activeOrchestrations"
+                    
+                    if [[ "$activeOrchestrations" == "false" ]]; then
                       echo "No active orchestrations running on the Data Processor - slot swapping can proceed"
                       exit 0
                     fi
   
                     attempts=$((attempts + 1))
+
+                    sleep $pollingTimeSeconds
                   
                   done
 
